# Generated by Django 4.1.3 on 2024-11-07 06:53

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('otp', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('full_name', models.CharField(default='', max_length=2000, null=True)),
                ('phone1', models.CharField(default='', max_length=2000, null=True)),
                ('phone2', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('is_reset_password', models.BooleanField(default=False, verbose_name='Reset Password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=2000)),
                ('year', models.IntegerField()),
                ('fuel', models.CharField(max_length=2000, verbose_name='Fuel Type')),
                ('make', models.CharField(max_length=2000)),
                ('kilos', models.CharField(max_length=2000)),
                ('transmission', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MultiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('price', models.IntegerField()),
                ('expire_date', models.DateTimeField()),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('cars', 'cars'), ('miscellaneous', 'miscellaneous')], max_length=2000)),
                ('car', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.car')),
                ('display', models.ManyToManyField(to='content.multiimage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('universal', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address_hash', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiwer_hash', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('universal', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='content.product')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('owner', models.CharField(max_length=2000)),
                ('expire_date', models.DateTimeField()),
                ('universal', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.multiimage')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('owner', models.CharField(max_length=2000, null=True)),
                ('expire_date', models.DateTimeField(null=True)),
                ('splashscreen', models.BooleanField(default=True)),
                ('home', models.BooleanField(default=True)),
                ('universal', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.multiimage')),
            ],
        ),
    ]
