# Generated by Django 4.1.4 on 2022-12-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='display',
        ),
    ]
