# Generated by Django 4.1.4 on 2022-12-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_product_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.ManyToManyField(to='content.multiimage'),
        ),
    ]
