# Generated by Django 4.1.3 on 2023-01-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_banner_created_alter_banner_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='display',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='expire_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='home',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='banner',
            name='owner',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='splashscreen',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='featuredad',
            name='display',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
