# Generated by Django 4.1.3 on 2022-12-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
