# Generated by Django 4.1.3 on 2023-01-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_banner_created_alter_banner_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.multiimage'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='home',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='owner',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='splashscreen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='featuredad',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.multiimage'),
        ),
    ]
