# Generated by Django 4.1.3 on 2022-12-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
