# Generated by Django 4.1.3 on 2022-12-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cars', 'cars'), ('others', 'others')], max_length=50),
        ),
    ]
