# Generated by Django 4.1.3 on 2023-01-16 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_banner_created_alter_banner_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=2000)),
                ('year', models.IntegerField()),
                ('fuel', models.CharField(max_length=2000, verbose_name='Fuel Type')),
                ('make', models.CharField(max_length=2000)),
                ('kilos', models.CharField(max_length=2000)),
                ('transmission', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cars', 'cars'), ('miscellaneous', 'miscellaneous')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='car',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.car'),
        ),
    ]
