# Generated by Django 4.1.3 on 2023-01-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_car_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='featuredad',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
