# Generated by Django 4.1.3 on 2022-12-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
    ]
