# Generated by Django 4.1.3 on 2022-12-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='universal',
            field=models.UUIDField(auto_created=True, blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='featuredad',
            name='universal',
            field=models.UUIDField(auto_created=True, blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='identifier',
            field=models.UUIDField(auto_created=True, blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='universal',
            field=models.UUIDField(auto_created=True, blank=True, editable=False, unique=True),
        ),
    ]
