# Generated by Django 4.1.3 on 2023-01-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_banner_link_alter_featuredad_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
