# Generated by Django 4.1.3 on 2022-12-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_banner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='universal',
            field=models.UUIDField(auto_created=True),
        ),
    ]
