# Generated by Django 4.1.3 on 2023-04-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_multiimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiwer_hash', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('universal', models.UUIDField()),
            ],
        ),
    ]
