# Generated by Django 4.1.3 on 2022-12-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_banner_universal'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
