# Generated by Django 4.1.3 on 2022-12-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_banner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='owner',
            field=models.CharField(default=False, max_length=30),
            preserve_default=False,
        ),
    ]
