# Generated by Django 4.1.3 on 2023-04-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.product'),
            preserve_default=False,
        ),
    ]
