# Generated by Django 4.1.3 on 2023-05-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='content.product'),
        ),
    ]
