# Generated by Django 4.1.3 on 2023-04-16 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_viewer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='universal',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
