# Generated by Django 4.1.3 on 2022-12-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_banner_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feacturedad',
            old_name='url',
            new_name='link',
        ),
    ]
