# Generated by Django 4.1.3 on 2022-12-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rename_url_feacturedad_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feacturedad',
            name='universal',
            field=models.UUIDField(auto_created=True),
        ),
    ]
