# Generated by Django 4.1.3 on 2026-07-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_viewer_universal'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='featuredad',
            name='title',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
