# Generated by Django 4.1.3 on 2022-12-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_feacturedad_universal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeacturedAd',
            new_name='FeaturedAd',
        ),
    ]
