# Generated by Django 5.2.16 on 2026-07-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_banner_title_featuredad_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='promotion_type',
            field=models.CharField(choices=[('fresh_arrivals', 'Fresh Arrivals'), ('monthend_specials', 'Monthend Specials'), ('customizable', 'Customizable Promo')], default='customizable', max_length=30),
        ),
    ]
