# Generated by Django 4.1.3 on 2022-12-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_rename_feacturedad_featuredad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='universal',
            field=models.UUIDField(auto_created=True, unique=True),
        ),
        migrations.AlterField(
            model_name='featuredad',
            name='universal',
            field=models.UUIDField(auto_created=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='identifier',
            field=models.UUIDField(auto_created=True, unique=True),
        ),
    ]
