# Generated by Django 4.1.3 on 2026-08-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_banner_promotion_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'permissions': [('manage_promotions', 'Can manage promotions')]},
        ),
        migrations.AlterModelOptions(
            name='featuredad',
            options={'permissions': [('manage_promotions', 'Can manage promotions')]},
        ),
    ]
