# Generated by Django 5.2.16 on 2026-08-05 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_banner_options_alter_featuredad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('promotion_type', models.CharField(choices=[('fresh_arrivals', 'Fresh Arrivals'), ('monthend_specials', 'Monthend Specials'), ('customizable', 'Customizable Promo')], default='customizable', max_length=30)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('owner', models.CharField(blank=True, max_length=2000, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('splashscreen', models.BooleanField(default=True)),
                ('home', models.BooleanField(default=True)),
                ('universal', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.multiimage')),
            ],
            options={
                'permissions': [('manage_promotions', 'Can manage promotions')],
            },
        ),
    ]
