# Generated by Django 4.1.3 on 2022-12-06 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_banner_universal_alter_featuredad_universal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredad',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
