# Generated by Django 5.2.16 on 2026-08-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='promotion_type',
            field=models.CharField(blank=True, default='', help_text='Enter a custom promotion type or use one of the standard promo categories.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(blank=True, default='', help_text='Enter a custom promotion type or use one of the standard promo categories.', max_length=2000),
        ),
    ]
