# Generated by Django 4.1.3 on 2022-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_multiimage_alter_product_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='display',
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.ManyToManyField(to='content.multiimage'),
        ),
    ]
