# Generated by Django 4.1.3 on 2022-12-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_user_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone1',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone2',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
