# Generated by Django 4.1.3 on 2022-12-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_user_full_name_alter_user_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
