# Generated by Django 4.1.3 on 2022-12-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_user_is_reset_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_reset_password',
            new_name='Reset Password',
        ),
    ]
