# Generated by Django 4.1.3 on 2022-12-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_rename_is_reset_password_user_reset password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Reset Password',
        ),
        migrations.AddField(
            model_name='user',
            name='is_reset_password',
            field=models.BooleanField(default=False, verbose_name='Reset Password'),
        ),
    ]
