# Generated by Django 4.1.3 on 2022-12-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
