# Generated by Django 4.1.3 on 2022-12-11 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
