# Generated by Django 4.1.3 on 2022-12-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_multiimage_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expire_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
