# Generated by Django 4.1.3 on 2022-12-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_alter_product_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='display',
        ),
    ]
