# Generated by Django 4.1.3 on 2022-12-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_remove_product_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.ManyToManyField(to='content.multiimage'),
        ),
    ]
